FROM diamol/golang AS builder 
COPY main.go .

Run go build -o /server


# app
FROM diamol/base

ENV USER=sixeyed

CMD ["/web/server"]

WORKDIR web
COPY index.html .
COPY --from=builder /server .

RUN chmod +x /web/server

EXPOSE 80
